local:
  dialect: postgres
  datasource: host=127.0.0.1 port=5432 dbname=sample user=sample password=sample sslmode=disable
  dir: sample
ci:
  dialect: postgres
  datasource: host=127.0.0.1 port=5432 dbname=sample user=sample password=sample sslmode=disable
  dir: sample
